package per.aniao.eatwell.bean

/**
 *
 * @author: hmei
 * @date: 2021/11/27
 * @email: huangmei@haohaozhu.com
 *
 */
val Vegetable = listOf(
    Triple("西红柿", "", "番茄"),
    Triple("土豆", "", "马铃薯"),
    Triple("洋葱", "", ""),
    Triple("娃娃菜", "", ""),
    Triple("包菜", "", "卷心菜"),
    Triple("白洋葱", "", ""),
    Triple("甜椒", "", "彩椒"),
    Triple("胡萝卜", "", "红萝卜"),
    Triple("白萝卜", "", ""),
    Triple("黄瓜", "", "青瓜"),
    Triple("玉米", "", ""),
    Triple("茄子", "", ""),
    Triple("南瓜", "", ""),
    Triple("白菜", "", ""),
    Triple("西兰花", "", ""),
    Triple("金针菇", "", ""),
    Triple("香菇", "", ""),
    Triple("大葱", "", ""),
    Triple("笋", "", ""),
    Triple("魔芋", "", ""),
    Triple("蒜苔", "", "蒜薹"),
    Triple("豆腐", "", ""),
    Triple("生菜", "", ""),
    Triple("白蘑菇", "", "口蘑"),
    Triple("海鲜菇", "", ""),
    Triple("蟹味菇", "", ""),
    Triple("小油菜", "", ""),
    Triple("冬瓜", "", ""),
    Triple("芹菜", "", ""),
    Triple("菠菜", "", ""),
    Triple("毛豆", "", ""),
    Triple("花生", "", ""),
    Triple("莲藕", "", ""),
    Triple("韭菜", "", ""),
    Triple("平菇", "", ""),
    Triple("青椒", "", ""),
    Triple("秋葵", "", ""),
    Triple("香菜", "", ""),
)

val SeaFood = listOf(
    Triple("螃蟹", "", ""),
    Triple("虾", "", ""),
    Triple("海胆", "", ""),
    Triple("扇贝", "", ""),
    Triple("生蚝", "", ""),
    Triple("花甲", "", ""),
    Triple("青口", "", ""),
    Triple("鱿鱼", "", ""),
)

val Meat = listOf(
    Triple("猪前腿肉", "", ""),
    Triple("猪蹄", "", ""),
    Triple("猪肋排", "", ""),
    Triple("猪五花", "", ""),
    Triple("猪肉馅", "", ""),
    Triple("猪脊骨", "", ""),
    Triple("猪里脊", "", ""),
    Triple("猪后退肉", "", ""),
    Triple("猪肚", "", ""),
    Triple("猪瘦肉", "", ""),
    Triple("猪筒骨", "", ""),
    Triple("猪梅花肉", "", ""),
    Triple("牛腩", "", ""),
    Triple("牛肉卷", "", ""),
    Triple("牛排骨", "", ""),
    Triple("牛里脊", "", ""),
    Triple("牛肉", "", ""),
    Triple("牛腱", "", ""),
    Triple("牛匙仁", "", ""),
    Triple("牛杂", "", ""),
    Triple("牛上脑", "", ""),
    Triple("牛排", "", ""),
    Triple("牛百叶", "", ""),
    Triple("羊腿", "", ""),
    Triple("羊肉卷", "", ""),
    Triple("羊排", "", ""),
    Triple("鸡腿", "", ""),
    Triple("鸡翅", "", ""),
    Triple("鸡胸", "", ""),
    Triple("鸡肉", "", ""),
    Triple("鸡爪", "", ""),
    Triple("鸭腿", "", ""),
    Triple("鸡蛋", "", ""),
    Triple("鸭蛋", "", ""),
    Triple("皮蛋", "", ""),
)

val Seasoning = listOf(
    Triple("蒜", "", ""),
    Triple("葱", "", ""),
    Triple("姜", "", ""),
    Triple("料酒", "", ""),
    Triple("老抽", "", ""),
    Triple("生抽", "", ""),
    Triple("鱼露", "", ""),
    Triple("芝麻油", "", ""),
    Triple("猪油", "", ""),
    Triple("黄油", "", ""),
    Triple("榨菜", "", ""),
    Triple("盐", "", ""),
    Triple("白砂糖", "", ""),
    Triple("冰糖", "", ""),
    Triple("芥末", "", ""),
    Triple("鸡精", "", ""),
    Triple("酵母", "", ""),
    Triple("陈醋", "", ""),
    Triple("白醋", "", ""),
    Triple("鸡精", "", ""),
    Triple("味精", "", ""),
    Triple("蚝油", "", ""),
    Triple("八角", "", ""),
    Triple("茴香", "", ""),
    Triple("孜然", "", ""),
    Triple("干辣椒", "", ""),
    Triple("辣椒面", "", ""),
    Triple("桂皮", "", ""),
    Triple("韩式辣酱", "", ""),
    Triple("老干妈", "", ""),
    Triple("豆瓣酱", "", ""),
)

val DriedFood = listOf(
    Triple("虾皮", "", ""),
    Triple("花菇", "", ""),
    Triple("木耳", "", ""),
    Triple("银耳", "", ""),
    Triple("大米", "", ""),
    Triple("糯米", "", ""),
    Triple("黄豆", "", ""),
    Triple("花生", "", ""),
    Triple("红豆", "", ""),
    Triple("绿豆", "", ""),
    Triple("紫菜", "", ""),
    Triple("挂面", "", ""),
    Triple("速冻饺子", "", ""),
    Triple("速冻汤圆", "", ""),
)